/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.curlp.capapresentacion;

import com.curlp.capapresentacion.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sanch
 */
public class JFFRegistroVacuna extends javax.swing.JFrame {

    /**
     * Creates new form JFFRegistroVacuna
     */
    public JFFRegistroVacuna() {
        initComponents();
    }
    public void abrirVentanaSelectorPaciente() throws SQLException, ParseException{
        JFFVisorDePaciente visorPaciente = new JFFVisorDePaciente(this);
        visorPaciente.setVisible(true);
    }
    
    public void abrirVentanaSelectorVacunador() throws SQLException, ParseException{
        JFFVisorDeVacunador visorVacunador = new JFFVisorDeVacunador(this);
        visorVacunador.setVisible(true);
    }
    
    public void abrirVentanaSelectorLote() throws SQLException, ParseException{
        JFFVisorDeLote visorLote = new JFFVisorDeLote(this);
        visorLote.setVisible(true);
    }

    public void abrirVentanaSelectorEstablecimiento() throws SQLException, ParseException{
        JFFVisorDeEstablecimiento visorEst = new JFFVisorDeEstablecimiento(this);
        visorEst.setVisible(true);
    }
    
    public void llenarDatosPaciente(String numIdentidad, String nombre, String apellido, String fechaNacimiento){
        jTFNumIdentidadPaciente.setText(numIdentidad);
        jTFNombrePaciente.setText(nombre);
        jTFApellidosPaciente.setText(apellido);
        jTFFechaNacimientoPaciente.setText(fechaNacimiento);
    }
    
    public void llenarDatosVacunador(String numIdentidad, String nombre, String apellido){
        JTFNumIdentidadVacunador.setText(numIdentidad);
        jTFNombreVacunador.setText(nombre);
        jTFApellidoVacunador.setText(apellido);
    }

    public void llenarDatosLote(String numLote, String fechaVencimiento, String marca){
        jTFNumLote.setText(numLote);
        jTFechaVencimiento.setText(fechaVencimiento);
        jTFmarcaVacuna.setText(marca);
    }
    
    public void llenarDatosEstablecimiento(String codigo, String nombre){
        jTFCodigoEstablecimiento.setText(codigo);
        jTFNombreEstablecimiento.setText(nombre);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPfranjaSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbUser = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnBuscarLote = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTFechaVencimiento = new javax.swing.JTextField();
        jTFNumLote = new javax.swing.JTextField();
        jDCFechaVacunacion = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jTFmarcaVacuna = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTFNumerodeRegistro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBtnBuscarEstablecimiento = new javax.swing.JButton();
        jTFNombreEstablecimiento = new javax.swing.JTextField();
        jTFCodigoEstablecimiento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jBtnBuscarVacunador = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTFApellidoVacunador = new javax.swing.JTextField();
        jTFNombreVacunador = new javax.swing.JTextField();
        JTFNumIdentidadVacunador = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jBtnBuscarPaciente = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTFFechaNacimientoPaciente = new javax.swing.JTextField();
        jTFApellidosPaciente = new javax.swing.JTextField();
        jTFNombrePaciente = new javax.swing.JTextField();
        jTFNumIdentidadPaciente = new javax.swing.JTextField();
        jPfranjaSuperior1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPfranjaSuperior.setBackground(new java.awt.Color(0, 153, 153));
        jPfranjaSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPfranjaSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 10));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 50, 50));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Registro de Vacunación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 30));
        jPanel1.add(jLbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Datos de Vacunación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("# de Lote Vacuna");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha de Vencimiento");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("# de Dosis");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jBtnBuscarLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBuscarLote.setForeground(new java.awt.Color(0, 153, 153));
        jBtnBuscarLote.setText("Buscar");
        jBtnBuscarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarLoteActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnBuscarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fecha de Aplicación");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel2.add(jTFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 210, 30));
        jPanel2.add(jTFNumLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 200, 30));

        jDCFechaVacunacion.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDCFechaVacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Marca Vacuna");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel2.add(jTFmarcaVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 710, 140));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Número de Registro:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        getContentPane().add(jTFNumerodeRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 157, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Datos del Establecimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Código  Establecimiento:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nombre Establecimiento");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jBtnBuscarEstablecimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBuscarEstablecimiento.setForeground(new java.awt.Color(0, 153, 153));
        jBtnBuscarEstablecimiento.setText("Buscar");
        jBtnBuscarEstablecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarEstablecimientoActionPerformed(evt);
            }
        });
        jPanel3.add(jBtnBuscarEstablecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 110, 30));
        jPanel3.add(jTFNombreEstablecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 200, 30));
        jPanel3.add(jTFCodigoEstablecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 157, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 710, 110));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Datos del Vacunador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Nombres:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Apellidos");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jBtnBuscarVacunador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBuscarVacunador.setForeground(new java.awt.Color(0, 153, 153));
        jBtnBuscarVacunador.setText("Buscar");
        jBtnBuscarVacunador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarVacunadorActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnBuscarVacunador, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 110, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Número de Identidad:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel4.add(jTFApellidoVacunador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 210, 30));
        jPanel4.add(jTFNombreVacunador, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 200, 30));
        jPanel4.add(JTFNumIdentidadVacunador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 157, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 710, 140));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)), "Datos del Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Nombres:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Apellidos");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jBtnBuscarPaciente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBuscarPaciente.setForeground(new java.awt.Color(0, 153, 153));
        jBtnBuscarPaciente.setText("Buscar");
        jBtnBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarPacienteActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnBuscarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 110, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Número de Identidad:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel5.add(jTFFechaNacimientoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, 30));
        jPanel5.add(jTFApellidosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 210, 30));
        jPanel5.add(jTFNombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 200, 30));
        jPanel5.add(jTFNumIdentidadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 157, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 710, 140));

        jPfranjaSuperior1.setBackground(new java.awt.Color(0, 153, 153));
        jPfranjaSuperior1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPfranjaSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 740, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        this.dispose();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jBtnBuscarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarLoteActionPerformed
        try {
            this.abrirVentanaSelectorLote();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar lotes", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar lotes", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBuscarLoteActionPerformed

    private void jBtnBuscarEstablecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarEstablecimientoActionPerformed
        try {
            this.abrirVentanaSelectorEstablecimiento();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar establecimientos", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar establecimientos", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBuscarEstablecimientoActionPerformed

    private void jBtnBuscarVacunadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarVacunadorActionPerformed
        try {
            this.abrirVentanaSelectorVacunador();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar vacunador", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar vacunador", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBuscarVacunadorActionPerformed

    private void jBtnBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarPacienteActionPerformed
        try {
            abrirVentanaSelectorPaciente();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar un paciente", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error al buscar un paciente", "COVA System", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnBuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFRegistroVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFRegistroVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFRegistroVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFRegistroVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFRegistroVacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFNumIdentidadVacunador;
    private javax.swing.JButton jBtnBuscarEstablecimiento;
    private javax.swing.JButton jBtnBuscarLote;
    private javax.swing.JButton jBtnBuscarPaciente;
    private javax.swing.JButton jBtnBuscarVacunador;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDCFechaVacunacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPfranjaSuperior;
    private javax.swing.JPanel jPfranjaSuperior1;
    private javax.swing.JTextField jTFApellidoVacunador;
    private javax.swing.JTextField jTFApellidosPaciente;
    private javax.swing.JTextField jTFCodigoEstablecimiento;
    private javax.swing.JTextField jTFFechaNacimientoPaciente;
    private javax.swing.JTextField jTFNombreEstablecimiento;
    private javax.swing.JTextField jTFNombrePaciente;
    private javax.swing.JTextField jTFNombreVacunador;
    private javax.swing.JTextField jTFNumIdentidadPaciente;
    private javax.swing.JTextField jTFNumLote;
    private javax.swing.JTextField jTFNumerodeRegistro;
    private javax.swing.JTextField jTFechaVencimiento;
    private javax.swing.JTextField jTFmarcaVacuna;
    // End of variables declaration//GEN-END:variables
}
