/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.curlp.presentacion;
import com.curlp.presentacion.vistasPaciente.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author davidmendoza
 */
public class JFFMain extends javax.swing.JFrame {

    /**
     * Creates new form JFFMain
     */
    public JFFMain() {
        initComponents();
    }
    public void lanzarVentanaSeleccion(){
       JFFSeleccion ventanaSeleccion = new JFFSeleccion();
       ventanaSeleccion.setVisible(true);
       this.setVisible(false);
    }
    public void nuevoPaciente(){
       JFFAgregarPacienteManual ventanaSeleccion = new JFFAgregarPacienteManual();
       ventanaSeleccion.setVisible(true);
       
    }
    
    public void eliminarPaciente(){
       JFFEliminarPaciente ventanaSeleccion = new JFFEliminarPaciente();
       ventanaSeleccion.setVisible(true);
       
    }
    
    public void modificarPaciente(){
       JFFModificarPaciente ventanaSeleccion = new JFFModificarPaciente();
       ventanaSeleccion.setVisible(true);
       
    }
    
    public void mostrarPacienteX(){
       JFFBuscarPaciente ventanaSeleccion = new  JFFBuscarPaciente();
       ventanaSeleccion.setVisible(true);
    }
    
    public void mostrarPacientes() throws SQLException{
       JFFmostrarPacientes ventanaSeleccion = new  JFFmostrarPacientes();
       ventanaSeleccion.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnVacunar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMControlVacunacion = new javax.swing.JMenu();
        jMIModificarVacunacion = new javax.swing.JMenuItem();
        jMIMostrarVacunacion = new javax.swing.JMenuItem();
        jMIBuscarVacunacion = new javax.swing.JMenuItem();
        jMIEliminarVacunacion = new javax.swing.JMenuItem();
        jMControlPacientes = new javax.swing.JMenu();
        jMIInsertarPaciente = new javax.swing.JMenuItem();
        jMIModificarPaciente = new javax.swing.JMenuItem();
        jMIEliminarPaciente = new javax.swing.JMenuItem();
        jMIbuscarPaciente = new javax.swing.JMenuItem();
        jMIMostarPacientes = new javax.swing.JMenuItem();
        jMControlVacunadores = new javax.swing.JMenu();
        jMIInsertarVacunador = new javax.swing.JMenuItem();
        jMIModificarVacunador = new javax.swing.JMenuItem();
        jMIEliminarVacunador = new javax.swing.JMenuItem();
        jMIMostarVacunadores = new javax.swing.JMenuItem();
        jMControlProfesiones = new javax.swing.JMenu();
        jMIInsertarProfecion = new javax.swing.JMenuItem();
        jMIModificarProfecion = new javax.swing.JMenuItem();
        jMIEliminarProfecion = new javax.swing.JMenuItem();
        jMIMostarProfeciones = new javax.swing.JMenuItem();
        jMControlEstablecimientos = new javax.swing.JMenu();
        jMIInsertarEstablecimiento = new javax.swing.JMenuItem();
        jMIModificarEstablecimiento = new javax.swing.JMenuItem();
        jMIEliminarEstablecimiento = new javax.swing.JMenuItem();
        jMIMostarEstablecimiento = new javax.swing.JMenuItem();
        jMControlFabricantes = new javax.swing.JMenu();
        jMIInsertarFabricante = new javax.swing.JMenuItem();
        jMIModificarFabricante = new javax.swing.JMenuItem();
        jMIEliminarFabricante = new javax.swing.JMenuItem();
        jMIMostarFabricantes = new javax.swing.JMenuItem();
        jMControlLotes = new javax.swing.JMenu();
        jMIInsertarLote = new javax.swing.JMenuItem();
        jMIModificarLote = new javax.swing.JMenuItem();
        jMIEliminarLote = new javax.swing.JMenuItem();
        jMIMostarLotes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 25));
        setLocationByPlatform(true);
        setName("JFFMain"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jBtnVacunar.setBackground(new java.awt.Color(51, 102, 255));
        jBtnVacunar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnVacunar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVacunar.setText("Iniciar Vacunacion");
        jBtnVacunar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnVacunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVacunarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jBtnVacunar, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jBtnVacunar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sin Derechos Reservados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(406, 406, 406))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMControlVacunacion.setText("Vacunaciones");

        jMIModificarVacunacion.setText("Modificar un registro");
        jMControlVacunacion.add(jMIModificarVacunacion);

        jMIMostrarVacunacion.setText("Mostrar registros");
        jMControlVacunacion.add(jMIMostrarVacunacion);

        jMIBuscarVacunacion.setText("Buscar un registro");
        jMControlVacunacion.add(jMIBuscarVacunacion);

        jMIEliminarVacunacion.setText("Eliminar registro");
        jMControlVacunacion.add(jMIEliminarVacunacion);

        jMenuBar1.add(jMControlVacunacion);

        jMControlPacientes.setText("   Pacientes");

        jMIInsertarPaciente.setText("Agregar");
        jMIInsertarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInsertarPacienteActionPerformed(evt);
            }
        });
        jMControlPacientes.add(jMIInsertarPaciente);

        jMIModificarPaciente.setText("Modificar");
        jMIModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIModificarPacienteActionPerformed(evt);
            }
        });
        jMControlPacientes.add(jMIModificarPaciente);

        jMIEliminarPaciente.setText("Eliminar");
        jMIEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEliminarPacienteActionPerformed(evt);
            }
        });
        jMControlPacientes.add(jMIEliminarPaciente);

        jMIbuscarPaciente.setText("Buscar");
        jMIbuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIbuscarPacienteActionPerformed(evt);
            }
        });
        jMControlPacientes.add(jMIbuscarPaciente);

        jMIMostarPacientes.setText("Mostrar todos");
        jMIMostarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMostarPacientesActionPerformed(evt);
            }
        });
        jMControlPacientes.add(jMIMostarPacientes);

        jMenuBar1.add(jMControlPacientes);

        jMControlVacunadores.setText("   Vacunadores");

        jMIInsertarVacunador.setText("Agregar");
        jMControlVacunadores.add(jMIInsertarVacunador);

        jMIModificarVacunador.setText("Modificar");
        jMControlVacunadores.add(jMIModificarVacunador);

        jMIEliminarVacunador.setText("Eliminar");
        jMControlVacunadores.add(jMIEliminarVacunador);

        jMIMostarVacunadores.setText("Mostrar todos");
        jMControlVacunadores.add(jMIMostarVacunadores);

        jMenuBar1.add(jMControlVacunadores);

        jMControlProfesiones.setText("  Profesiones");

        jMIInsertarProfecion.setText("Agregar");
        jMControlProfesiones.add(jMIInsertarProfecion);

        jMIModificarProfecion.setText("Modificar");
        jMControlProfesiones.add(jMIModificarProfecion);

        jMIEliminarProfecion.setText("Eliminar");
        jMControlProfesiones.add(jMIEliminarProfecion);

        jMIMostarProfeciones.setText("Mostrar todos");
        jMControlProfesiones.add(jMIMostarProfeciones);

        jMenuBar1.add(jMControlProfesiones);

        jMControlEstablecimientos.setText("   Centros de Vacunacion");

        jMIInsertarEstablecimiento.setText("Agregar");
        jMControlEstablecimientos.add(jMIInsertarEstablecimiento);

        jMIModificarEstablecimiento.setText("Modificar");
        jMControlEstablecimientos.add(jMIModificarEstablecimiento);

        jMIEliminarEstablecimiento.setText("Eliminar");
        jMControlEstablecimientos.add(jMIEliminarEstablecimiento);

        jMIMostarEstablecimiento.setText("Mostrar todos");
        jMControlEstablecimientos.add(jMIMostarEstablecimiento);

        jMenuBar1.add(jMControlEstablecimientos);

        jMControlFabricantes.setText("   Fabricantes");

        jMIInsertarFabricante.setText("Agregar");
        jMControlFabricantes.add(jMIInsertarFabricante);

        jMIModificarFabricante.setText("Modificar");
        jMControlFabricantes.add(jMIModificarFabricante);

        jMIEliminarFabricante.setText("Eliminar");
        jMControlFabricantes.add(jMIEliminarFabricante);

        jMIMostarFabricantes.setText("Mostrar todos");
        jMControlFabricantes.add(jMIMostarFabricantes);

        jMenuBar1.add(jMControlFabricantes);

        jMControlLotes.setText("  Lotes");

        jMIInsertarLote.setText("Agregar");
        jMControlLotes.add(jMIInsertarLote);

        jMIModificarLote.setText("Modificar");
        jMControlLotes.add(jMIModificarLote);

        jMIEliminarLote.setText("Eliminar");
        jMControlLotes.add(jMIEliminarLote);

        jMIMostarLotes.setText("Mostrar todos");
        jMControlLotes.add(jMIMostarLotes);

        jMenuBar1.add(jMControlLotes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVacunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVacunarActionPerformed
        lanzarVentanaSeleccion();
    }//GEN-LAST:event_jBtnVacunarActionPerformed

    private void jMIInsertarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInsertarPacienteActionPerformed
        nuevoPaciente();
    }//GEN-LAST:event_jMIInsertarPacienteActionPerformed

    private void jMIEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEliminarPacienteActionPerformed
        eliminarPaciente();
    }//GEN-LAST:event_jMIEliminarPacienteActionPerformed

    private void jMIModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIModificarPacienteActionPerformed
        modificarPaciente();
    }//GEN-LAST:event_jMIModificarPacienteActionPerformed

    private void jMIbuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIbuscarPacienteActionPerformed
        mostrarPacienteX();
       
    }//GEN-LAST:event_jMIbuscarPacienteActionPerformed

    private void jMIMostarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMostarPacientesActionPerformed
        try {
            mostrarPacientes();
        } catch (SQLException ex) {
            Logger.getLogger(JFFMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIMostarPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVacunar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMControlEstablecimientos;
    private javax.swing.JMenu jMControlFabricantes;
    private javax.swing.JMenu jMControlLotes;
    private javax.swing.JMenu jMControlPacientes;
    private javax.swing.JMenu jMControlProfesiones;
    private javax.swing.JMenu jMControlVacunacion;
    private javax.swing.JMenu jMControlVacunadores;
    private javax.swing.JMenuItem jMIBuscarVacunacion;
    private javax.swing.JMenuItem jMIEliminarEstablecimiento;
    private javax.swing.JMenuItem jMIEliminarFabricante;
    private javax.swing.JMenuItem jMIEliminarLote;
    private javax.swing.JMenuItem jMIEliminarPaciente;
    private javax.swing.JMenuItem jMIEliminarProfecion;
    private javax.swing.JMenuItem jMIEliminarVacunacion;
    private javax.swing.JMenuItem jMIEliminarVacunador;
    private javax.swing.JMenuItem jMIInsertarEstablecimiento;
    private javax.swing.JMenuItem jMIInsertarFabricante;
    private javax.swing.JMenuItem jMIInsertarLote;
    private javax.swing.JMenuItem jMIInsertarPaciente;
    private javax.swing.JMenuItem jMIInsertarProfecion;
    private javax.swing.JMenuItem jMIInsertarVacunador;
    private javax.swing.JMenuItem jMIModificarEstablecimiento;
    private javax.swing.JMenuItem jMIModificarFabricante;
    private javax.swing.JMenuItem jMIModificarLote;
    private javax.swing.JMenuItem jMIModificarPaciente;
    private javax.swing.JMenuItem jMIModificarProfecion;
    private javax.swing.JMenuItem jMIModificarVacunacion;
    private javax.swing.JMenuItem jMIModificarVacunador;
    private javax.swing.JMenuItem jMIMostarEstablecimiento;
    private javax.swing.JMenuItem jMIMostarFabricantes;
    private javax.swing.JMenuItem jMIMostarLotes;
    private javax.swing.JMenuItem jMIMostarPacientes;
    private javax.swing.JMenuItem jMIMostarProfeciones;
    private javax.swing.JMenuItem jMIMostarVacunadores;
    private javax.swing.JMenuItem jMIMostrarVacunacion;
    private javax.swing.JMenuItem jMIbuscarPaciente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
